"""initial

Revision ID: a60dcd2bc0eb
Revises: 
Create Date: 2026-05-06 09:49:47.776187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a60dcd2bc0eb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cargas_etl',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('fecha_carga', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('mes', sa.String(length=2), nullable=False),
    sa.Column('anio', sa.String(length=4), nullable=False),
    sa.Column('archivos', sa.Text(), nullable=True),
    sa.Column('total_registros', sa.Integer(), nullable=True),
    sa.Column('registros_nuevos', sa.Integer(), nullable=True),
    sa.Column('registros_dup', sa.Integer(), nullable=True),
    sa.Column('errores', sa.Integer(), nullable=True),
    sa.Column('advertencias', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('detalle', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paquetes_alimentarios',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('documento', sa.String(length=20), nullable=False),
    sa.Column('autorizacion', sa.String(length=50), nullable=True),
    sa.Column('nombre_representante', sa.String(length=200), nullable=False),
    sa.Column('genero', sa.String(length=20), nullable=True),
    sa.Column('cantidad_paquetes', sa.Integer(), nullable=True),
    sa.Column('programa', sa.String(length=200), nullable=True),
    sa.Column('comuna', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('nombre_punto', sa.String(length=200), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('referente', sa.String(length=200), nullable=True),
    sa.Column('fecha_programada', sa.Date(), nullable=True),
    sa.Column('fecha_entrega', sa.Date(), nullable=True),
    sa.Column('grupo', sa.String(length=50), nullable=True),
    sa.Column('horario', sa.String(length=100), nullable=True),
    sa.Column('resultado_convocatoria', sa.String(length=100), nullable=True),
    sa.Column('quien_sdm', sa.String(length=100), nullable=True),
    sa.Column('responsable', sa.String(length=200), nullable=True),
    sa.Column('otro_telefono', sa.String(length=30), nullable=True),
    sa.Column('responsable6', sa.String(length=200), nullable=True),
    sa.Column('anio_entrega', sa.Integer(), nullable=True),
    sa.Column('mes_entrega', sa.Integer(), nullable=True),
    sa.Column('mes_nombre', sa.String(length=20), nullable=True),
    sa.Column('dia_entrega', sa.Integer(), nullable=True),
    sa.Column('entregado', sa.Boolean(), nullable=True),
    sa.Column('cargado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('archivo_origen', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('documento', 'fecha_entrega', name='uq_documento_fecha_entrega')
    )
    op.create_index(op.f('ix_paquetes_alimentarios_documento'), 'paquetes_alimentarios', ['documento'], unique=False)
    op.create_index(op.f('ix_paquetes_alimentarios_fecha_entrega'), 'paquetes_alimentarios', ['fecha_entrega'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paquetes_alimentarios_fecha_entrega'), table_name='paquetes_alimentarios')
    op.drop_index(op.f('ix_paquetes_alimentarios_documento'), table_name='paquetes_alimentarios')
    op.drop_table('paquetes_alimentarios')
    op.drop_table('cargas_etl')
    # ### end Alembic commands ###
