"""initial

Revision ID: ccd6a360924d
Revises: a60dcd2bc0eb
Create Date: 2026-05-06 10:11:36.634294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ccd6a360924d'
down_revision: Union[str, None] = 'a60dcd2bc0eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
